name: llama_in_dart
description: Dart FFI test with llama.cpp
version: 1.0.0
repository: https://github.com/SeongminJaden/llama_in_dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
